/**
 * City Maps Index — World of Myrdae
 * Thin registry: id, name, image paths only. No pins or labels here.
 * Pin/label data lives in js/cities/<id>.js, loaded on demand.
 */
const CITY_MAPS = [
  { id: "tratta"                  , name: "Tratta"                  , image: "images/cities/tratta/tratta.PNG", previewImage: "images/cities/tratta/tratta.PNG" },
  { id: "emberstran"              , name: "Emberstran"              , image: "images/cities/emberstran/emberstran.PNG", previewImage: "images/cities/emberstran/emberstran.PNG" },
  { id: "nauldeaus"               , name: "Nauldeaus"               , image: "images/cities/nauldeaus/nauldeaus.PNG", previewImage: "images/cities/nauldeaus/nauldeaus.PNG" },
  { id: "adsuren"                 , name: "Adsuren"                 , image: "images/cities/adsuren/adsuren.PNG", previewImage: "images/cities/adsuren/adsuren.PNG" },
  { id: "annagos"                 , name: "Annagos"                 , image: "images/cities/annagos/annagos.png", previewImage: "images/cities/annagos/annagos.png" },
  { id: "onaren"                  , name: "Onaren"                  , image: "images/cities/onaren/onaren.PNG", previewImage: "images/cities/onaren/onaren.PNG" },
  { id: "scarwatch-hold"          , name: "Scarwatch Hold"          , image: "images/cities/scarwatch-hold/scarwatch-hold.png", previewImage: "images/cities/scarwatch-hold/scarwatch-hold.png" },
  { id: "basctdelm"               , name: "basctdelm"               , image: "images/cities/basctdelm/basctdelm.PNG", previewImage: "images/cities/basctdelm/basctdelm.PNG" },
  { id: "basinpass"               , name: "Basinpass"               , image: "images/cities/basinpass/basinpass.png", previewImage: "images/cities/basinpass/basinpass.png" },
  { id: "shademoor"               , name: "Shademoor"               , image: "images/cities/shademoor/shademoor.png", previewImage: "images/cities/shademoor/shademoor.png" },
  { id: "abbey-of-mont-rest"      , name: "Abbey of Mont Rest"      , image: "images/cities/abbey-of-mont-rest/abbey-of-mont-rest.png", previewImage: undefined },
  { id: "farview"                 , name: "Farview"                 , image: "images/cities/farview/farview.png", previewImage: "images/cities/farview/farview.png" },
  { id: "glaspero"                , name: "Glaspero"                , image: "images/cities/glaspero/glaspero.png", previewImage: "images/cities/glaspero/glaspero.png" },
  { id: "greenvale"               , name: "Greenvale"               , image: "images/cities/greenvale/greenvale.png", previewImage: "images/cities/greenvale/greenvale.png" },
  { id: "climbor"                 , name: "Climbor"                 , image: "images/cities/climbor/climbor.png", previewImage: "images/cities/climbor/climbor.png" },
  { id: "everlight"               , name: "Everlight"               , image: "images/cities/everlight/everlight.png", previewImage: "images/cities/everlight/everlight.png" },
  { id: "aerley"                  , name: "Aerley"                  , image: "images/cities/aerley/aerley.png", previewImage: "images/cities/aerley/aerley.png" },
  { id: "olestack"                , name: "Ole'stack"               , image: "images/cities/olestack/olestack.png", previewImage: "images/cities/olestack/olestack.png" },
  { id: "sandgrave"               , name: "Sandgrave"               , image: "images/cities/sandgrave/sandgrave.png", previewImage: "images/cities/sandgrave/sandgrave.png" },
  { id: "kallilos"                , name: "Kallilos"                , image: "images/cities/kallilos/kallilos.png", previewImage: "images/cities/kallilos/kallilos.png" },
  { id: "sari-lenora"             , name: "Sari Lenora"             , image: "images/cities/sari-lenora/sari-lenora.png", previewImage: "images/cities/sari-lenora/sari-lenora.png" },
  { id: "clador"                  , name: "Clador"                  , image: "images/cities/clador/clador.png", previewImage: "images/cities/clador/clador.png" },
  { id: "ulgrey"                  , name: "Ulgrey"                  , image: "images/cities/ulgrey/ulgrey.png", previewImage: "images/cities/ulgrey/ulgrey.png" },
  { id: "trailpoint"              , name: "Trailpoint"              , image: "images/cities/trailpoint/trailpoint.png", previewImage: "images/cities/trailpoint/trailpoint.png" },
  { id: "farnsby-port"            , name: "Farnsby Port"            , image: "images/cities/farnsby-port/farnsby-port.png", previewImage: "images/cities/farnsby-port/farnsby-port.png" },
  { id: "dunduar"                 , name: "Dunduar"                 , image: "images/cities/dunduar/dunduar.png", previewImage: "images/cities/dunduar/dunduar.png" },
  { id: "nuwharf"                 , name: "Nuwharf"                 , image: "images/cities/nuwharf/nuwharf.png", previewImage: "images/cities/nuwharf/nuwharf.png" },
  { id: "talbesar"                , name: "Tal'besar Ruins"         , image: "images/cities/talbesar/talbesar.png", previewImage: "images/cities/talbesar/talbesar.png" },
  { id: "scarbrook"               , name: "Scarbrook"               , image: "images/cities/scarbrook/scarbrook.png", previewImage: "images/cities/scarbrook/scarbrook.png" },
  { id: "nebisill"                , name: "Nebisill"                , image: "images/cities/nebisill/nebisill.png", previewImage: "images/cities/nebisill/nebisill.png" },
  { id: "boldshire"               , name: "Boldshire"               , image: "images/cities/boldshire/boldshire.png", previewImage: "images/cities/boldshire/boldshire.png" },
  { id: "dryrock"                 , name: "Dryrock"                 , image: "images/cities/dryrock/dryrock.png", previewImage: "images/cities/dryrock/dryrock.png" },
  { id: "sunbay"                  , name: "Sunbay"                  , image: "images/cities/sunbay/sunbay.png", previewImage: "images/cities/sunbay/sunbay.png" },
  { id: "ahndashere"              , name: "Ahndashere"              , image: "images/cities/ahndashere/scetch.png", previewImage: "images/cities/ahndashere/scetch.png" },
  { id: "alburest"                , name: "Alburest"                , image: "images/cities/alburest/alburest.png", previewImage: "images/cities/alburest/alburest.png" },
  { id: "buvero"                  , name: "Buvero"                  , image: "images/cities/buvero/scetch.png", previewImage: "images/cities/buvero/scetch.png" },
  { id: "destons-trading-post"    , name: "Destons Trading Post"    , image: "images/cities/destons-trading-post/scetch.png", previewImage: "images/cities/destons-trading-post/scetch.png" },
  { id: "dha-chaomhnoir"          , name: "Dha Chaomhnoir"          , image: "images/cities/dha-chaomhnoir/scetch.png", previewImage: "images/cities/dha-chaomhnoir/scetch.png" },
  { id: "fal-thalor"              , name: "Fal'Thalor"              , image: "images/cities/fal-thalor/scetch.png", previewImage: "images/cities/fal-thalor/scetch.png" },
  { id: "felden"                  , name: "Felden"                  , image: "images/cities/felden/crest.png", previewImage: "images/cities/felden/crest.png" },
  { id: "ferndale"                , name: "Ferndale"                , image: "images/cities/ferndale/crest.png", previewImage: "images/cities/ferndale/crest.png" },
  { id: "gevakaln"                , name: "Gevakaln"                , image: "images/cities/gevakaln/scetch.png", previewImage: "images/cities/gevakaln/scetch.png" },
  { id: "habadin"                 , name: "Habadin"                 , image: "images/cities/habadin/scetch.png", previewImage: "images/cities/habadin/scetch.png" },
  { id: "harbok"                  , name: "Harbok"                  , image: "images/cities/harbok/scetch.png", previewImage: "images/cities/harbok/scetch.png" },
  { id: "hesfal"                  , name: "Hesfal"                  , image: "images/cities/hesfal/crest.png", previewImage: "images/cities/hesfal/crest.png" },
  { id: "lehnthruakk"             , name: "Lehnthru'akk"            , image: "images/cities/lehnthruakk/scetch.png", previewImage: "images/cities/lehnthruakk/scetch.png" },
  { id: "lenshur"                 , name: "Lenshur"                 , image: "images/cities/lenshur/scetch.png", previewImage: "images/cities/lenshur/scetch.png" },
  { id: "leoning"                 , name: "Leoning"                 , image: "images/cities/leoning/scetch.png", previewImage: "images/cities/leoning/scetch.png" },
  { id: "lurdoba"                 , name: "Lurdoba"                 , image: "images/cities/lurdoba/scetch.png", previewImage: "images/cities/lurdoba/scetch.png" },
  { id: "mistforge"               , name: "Mistforge"               , image: "images/cities/mistforge/scetch.png", previewImage: "images/cities/mistforge/scetch.png" },
  { id: "oldport"                 , name: "Oldport"                 , image: "images/cities/oldport/crest.png", previewImage: "images/cities/oldport/crest.png" },
  { id: "olmorrey"                , name: "Ol'Morrey"               , image: "images/cities/olmorrey/scetch.png", previewImage: "images/cities/olmorrey/scetch.png" },
  { id: "palason"                 , name: "Palason"                 , image: "images/cities/palason/scetch.png", previewImage: "images/cities/palason/scetch.png" },
  { id: "qaldynn"                 , name: "Qal'dynn"                , image: "images/cities/qaldynn/crest.png", previewImage: "images/cities/qaldynn/crest.png" },
  { id: "staghaven"               , name: "Staghaven"               , image: "images/cities/staghaven/scetch.png", previewImage: "images/cities/staghaven/scetch.png" },
  { id: "stoneshore"              , name: "Stoneshore"              , image: "images/cities/stoneshore/scetch.png", previewImage: "images/cities/stoneshore/scetch.png" },
  { id: "sulura"                  , name: "Sulura"                  , image: "images/cities/sulura/scetch.png", previewImage: "images/cities/sulura/scetch.png" },
  { id: "tarnsport"               , name: "Tarnsport"               , image: "images/cities/tarnsport/scetch.png", previewImage: "images/cities/tarnsport/scetch.png" },
  { id: "thrargael"               , name: "Thrargael"               , image: "images/cities/thrargael/crest.png", previewImage: "images/cities/thrargael/crest.png" },
  { id: "tynevale"                , name: "Tyne'vale"               , image: "images/cities/tynevale/crest.png", previewImage: "images/cities/tynevale/crest.png" },
  { id: "tyrynder"                , name: "Tyrynder"                , image: "images/cities/tyrynder/scetch.png", previewImage: "images/cities/tyrynder/scetch.png" },
  { id: "ulkef"                   , name: "Ulkef"                   , image: "images/cities/ulkef/scetch.png", previewImage: "images/cities/ulkef/scetch.png" },
  { id: "waypoint"                , name: "Waypoint"                , image: "images/cities/waypoint/scetch.png", previewImage: "images/cities/waypoint/scetch.png" },
  { id: "wheldrake"               , name: "Wheldrake"               , image: "images/cities/wheldrake/scetch.png", previewImage: "images/cities/wheldrake/scetch.png" },
];
