/**
 * World of Myrdae - Default Location Database
 * 
 * This file contains the default data for locations, roads, and regions.
 * It is loaded as a script to bypass CORS restrictions when running locally via file:// protocol.
 */

const WORLD_LOCATIONS = {
    "locations": [
        {
            "id": "otesurr-mountains",
            "name": "Otesurr\nMountains",
            "type": "region",
            "x": 81.7,
            "y": 25.6,
            "region": "Otesurr Mountains",
            "description": "The Otesurr Mountains are a vast mountain range in the far northeast of Myrdae.",
            "fontSize": 20,
            "opacity": 0.5,
            "markerSize": 0.0,
            "labelOffsetX": 10,
            "labelOffsetY": 3,
            "fontFamily": "Cinzel Decorative"
        },
        {
            "id": "lurdoba",
            "name": "Lurdoba",
            "type": "city",
            "x": 77.7,
            "y": 31.7,
            "region": "Otesurr Mountains",
            "description": "A tundra town in the far northeast.",
            "fontFamily": "Garamond MT",
            "fontSize": 18,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.15,
            "markerOffsetX": 10,
            "markerOffsetY": 0,
            "labelOffsetX": -2,
            "labelOffsetY": -13
        },
        {
            "id": "kallilos",
            "name": "Kallilos",
            "type": "town",
            "x": 78.3,
            "y": 32.3,
            "region": "Otesurr Mountains",
            "description": "A town off the coast of The Broken Deep.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 12,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "sari-lenora",
            "name": "Sari Lenora",
            "type": "town",
            "x": 77.9,
            "y": 34.4,
            "region": "Otesurr Mountains",
            "description": "A rugged northern settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "clador",
            "name": "Clador",
            "type": "town",
            "x": 77.4,
            "y": 36.3,
            "region": "Otesurr Mountains",
            "description": "A rugged northern settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "buvero",
            "name": "Buvero",
            "type": "town",
            "x": 76.0,
            "y": 35.9,
            "region": "Otesurr Mountains",
            "description": "A rugged mountain settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "sulura",
            "name": "Sulura",
            "type": "city",
            "x": 74.34,
            "y": 35.4,
            "region": "Otesurr Mountains",
            "description": "A tundra town in the far northeast.",
            "fontFamily": "Garamond MT",
            "fontSize": 18,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.15,
            "markerOffsetX": 10,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "sunbay",
            "name": "Sunbay",
            "type": "town",
            "x": 73.7,
            "y": 37.1,
            "region": "Otesurr Mountains",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "sands-of-the-dead",
            "name": "Sands of the\nDead",
            "type": "region",
            "x": 76.0,
            "y": 40.0,
            "region": "Sands of the Dead",
            "description": "Sands of the Dead",
            "fontSize": 20,
            "opacity": 0.5,
            "fontFamily": "Garamond MT",
            "fontWeight": "300",
            "markerSize": 0.0,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "ahnassa",
            "name": "Ahnassa",
            "type": "town",
            "x": 72.9,
            "y": 38.2,
            "region": "Otesurr Mountains",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "hesfal",
            "name": "Hesfal",
            "type": "town",
            "x": 71.8,
            "y": 40.5,
            "region": "Sands of the Dead",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": -48,
            "labelOffsetY": 9
        },
        {
            "id": "boneforge",
            "name": "Boneforge",
            "type": "town",
            "x": 73.3,
            "y": 41.1,
            "region": "Sands of the Dead",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 3
        },
        {
            "id": "deadfield",
            "name": "Deadfield",
            "type": "city",
            "x": 74.8,
            "y": 42.0,
            "region": "Sands of the Dead",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 18,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.15,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 10,
            "labelOffsetY": 15
        },
        {
            "id": "torpoint",
            "name": "Torpoint",
            "type": "town",
            "x": 74.1,
            "y": 42.8,
            "region": "Sands of the Dead",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": -57,
            "labelOffsetY": 3
        },
        {
            "id": "sulport",
            "name": "Sulport",
            "type": "town",
            "x": 71.0,
            "y": 38.2,
            "region": "Sands of the Dead",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 0,
            "labelOffsetY": -10
        },
        {
            "id": "ripshod-bay",
            "name": "Ripshod Bay",
            "type": "water",
            "x": 72.4,
            "y": 37.8,
            "region": "Ripshod Bay",
            "description": "Ripshod Bay",
            "fontFamily": "Garamond MT",
            "fontSize": 18,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "opacity": 0.5,
            "markerSize": 0.0,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 0,
            "labelOffsetY": 0
        },
        {
            "id": "tratta",
            "name": "Tratta",
            "type": "city",
            "x": 70.6,
            "y": 35.9,
            "region": "Sands of the Dead",
            "description": "A coastal settlement.",
            "fontFamily": "Garamond MT",
            "fontSize": 18,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.15,
            "markerOffsetX": 11,
            "markerOffsetY": 0,
            "labelOffsetX": -20,
            "labelOffsetY": -13
        },
        {
            "id": "del-bris",
            "name": "Del'Bris",
            "type": "town",
            "x": 70.3,
            "y": 38.7,
            "region": "Ripshod Bay",
            "description": "Ripshod Bay",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 5,
            "labelOffsetY": 16
        },
        {
            "id": "yearning-slough",
            "name": "Yearning\nSlough",
            "type": "region",
            "x": 69.6,
            "y": 39.1,
            "region": "Yearning Slough",
            "description": "Yearning Slough",
            "fontFamily": "Garamond MT",
            "fontSize": 16,
            "fontWeight": "300",
            "opacity": 0.5,
            "markerSize": 0.0,
            "markerOffsetX": 0,
            "markerOffsetY": 0,
            "labelOffsetX": 0,
            "labelOffsetY": 0
        },
        {
            "id": "azure-depths",
            "name": "The Azure\nDepths",
            "type": "water",
            "x": 25.0,
            "y": 75.0,
            "region": "The Great Sea",
            "description": "Deep, mysterious waters located off the southwest coast.",
            "fontFamily": "Garamond MT",
            "fontSize": 18,
            "opacity": 0.8,
            "markerSize": 0.0,
            "markerOffsetX": 0,
            "markerOffsetY": 0,
            "labelOffsetX": 0,
            "labelOffsetY": 0
        },
        {
            "id": "greenvale",
            "name": "Greenvale",
            "type": "town",
            "x": 69.5,
            "y": 40.5,
            "region": "Yearning Slough",
            "description": "Ripshod Bay",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": 5,
            "labelOffsetY": 16
        },
        {
            "id": "lehnthruakk",
            "name": "Lehnthru'akk",
            "type": "town",
            "x": 68.8,
            "y": 39.3,
            "region": "Yearning Slough",
            "description": "Ripshod Bay",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": -82,
            "labelOffsetY": 9
        },
        {
            "id": "zovraesdrias-hollow",
            "name": "Zovraesdria's\n   Hollow",
            "type": "poi",
            "x": 68.3,
            "y": 38.8,
            "region": "Yearning Slough",
            "description": "",
            "fontFamily": "Garamond MT",
            "fontSize": 14,
            "fontStyle": "Italic",
            "fontWeight": "300",
            "markerSize": 0.3,
            "markerOffsetX": 16,
            "markerOffsetY": 0,
            "labelOffsetX": -60,
            "labelOffsetY": -16
        }
    ],
    "roads": []
};
