window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["adsuren"] = {
  id: "adsuren",
  name: "Adsuren",
  image: "images/cities/adsuren/adsuren.PNG",
  previewImage: "images/cities/adsuren/adsuren.PNG",
  pins: [
    { n:  1, x: 26.2, y: 27.9, name: "The Graying Grotto", type: "tavern", desc: "The Graying Grotto is the premiere inn and tavern for those who are visiting Adsuren. Its large, once warm brown but now graying wooden frame is topped with a gray thatch. Despite its old and worn look, the inside is as warm and fresh as ever. Large round tables dot most of the square footage with a curved bar that hugs the right wall. ", size: 1.4 },
    { n:  2, x: 45.0, y: 26.4, name: "Adsuren Stables", type: "stables", desc: "This is a simple stable, housed near the Graying Grotto run by Roibeart Cuimein", size: 1.4 },
    { n:  3, x: 63.5, y: 8.5, name: "Mage Tower", type: "tower", desc: "This small tower was built around the 1210’s by an aspiring young mage. It sits just outside the town proper as a 3-story structure. Its first floor is what is seen by guests of the tower and it has a small kitchen and resting area. The other floors, while not frequently seen, are presumed to be a bedroom/study for the mage. In times when the mage is not around, the tower's door seems to be shut and locked by a powerful enchantment.", size: 1.4 },
    { n:  4, x: 70.7, y: 29.2, name: "Ethea's Stone", type: "landmark", desc: "Ethea’s Stone is the only completely stone structure in the village.  Its massive frame houses two chimneys for expelling smoke. Inside the large building, there are always a small handful of smiths or apprentices who are working on various wears, led by a pair of “siblings,” Nosgrim and Alfonita.This large smithy is located near the river’s edge and uses some of the water to cool down the forge when needed. The building is often lined with fine armor, blades, spears, bows, maces, and almost any weapons one can think of. \n", size: 1.4 },
    { n:  5, x: 80.9, y: 16.4, name: "Tanner", type: "shop", desc: "On the north side of the village resides a simple, dark stoned hut with a freshly thatched roof that serves as a tanner and leatherworker for the village. Inside you can find all sorts of leather goods, from boots, to sheaths, to armor and much more. Almadia Oriroris takes pride in her work and wears her own goods on a daily basis. She also occasionally sends hunters out to get more exotic leathers for her to work on.\n", size: 1.4 },
    { n:  6, x: 81.7, y: 38.1, name: "The Rugged Rooster", type: "tavern", desc: "The Rugged Rooster is a general store that sits as close to the river as any building could. The building's older design beautifully showcases the remarkable wonders a determined person can create through sheer hard work. The once proud, vibrant wooden walls are now dulled and grown over with moss and vines. Various sections of the roof have been replaced over time, resulting in an uneven, patchwork appearance where the materials don't entirely match. ", size: 1.4 },
    { n:  7, x: 73.8, y: 54.0, name: "The Falling Fish", type: "tavern", desc: "The Falling Fish is the local tavern for the village folk of Adsuren. It is a humble establishment that serves customers on the first floor, while the second floor is where the workers and owners sleep. Stepping into the Falling Fish, one immediately notices that a completely round bar dominates the center of the room. The dark wood interior is dimly lit by a plethora of orange lanterns or wide candle sticks. In the left foremost corner of the room, there is a large statue of a fish descending down a moving waterfall. ", size: 1.4 },
    { n:  8, x: 58.5, y: 66.9, name: "Spider's Silk", type: "shop", desc: "The Spider’s Silk is an elegant dark stone and dark roofed building built beneath the shade of two large willow-like trees. Multiple threads string out between the trees and the building, holding various lanterns that cast a faint purple glow, shining beautifully once night falls. Inside the shop, a large room serves as the meeting place between Anabu and his customers. ", size: 1.4 },
    { n:  9, x: 48.4, y: 55.3, name: "Guard Post", type: "garrison", desc: "Positioned near the heart of town, the Adsuren Guard Post is a sizable structure with a defensive tower built off to one side. The building itself serves as a meeting place for the Watch, as well as a small armory, a barracks, and housing for the Captain of the Watch, Captain Alinia Sarralei. To the side of the building, is a stone and wood tower that serves as a good watchpoint with a prison for criminals underneath.", size: 1.4 },
    { n: 10, x: 47.5, y: 66.5, name: "Adsuren Center", type: "landmark", desc: "The Adsuren Center is at the physical center of the village, though the market feels like the real heart of power for the village. Intendant Eyovar Dunajor rules over the town from here with a couple of assistants. The main building has a lobby, a small library, a centralized meeting area, a few smaller meeting areas for the public, and some back rooms that are reserved for officials who meet for important matters. ", size: 1.5 },
    { n: 11, x: 58.6, y: 87.7, name: "Intendant's House", type: "landmark", desc: "Home of the town intendant.", size: 1.4 },
    { n: 12, x: 14.6, y: 83.2, name: "Nature's Oratory", type: "temple", desc: "Nature’s Oratory is an old temple that was dedicated to the goddess of life before the Awakening when Adsuren was first settled. It was built before the market was as prominent, but still stands today. The Oratory is constructed from the dark stone sourced from the Western Mountain and roofed with deep purple, dyed clay tiles. Its exterior is covered in carefully maintained vines, and a beautiful garden borders each side of the building. A simple graveyard is situated behind the Oratory.", size: 1.4 },
    { n: 13, x: 29.8, y: 81.6, name: "Gannon's House", type: "House", desc: "Cult member" },
  ],
  namedLabels: [
    { id: "docks", name: "Docks", x: 90.2, y: 50.9, type: "harbor", desc: "Adsuren’s location on the edge of a large river necessitates massive docks. Remarkably, these structures have remained in high perfect condition since their construction at the settlement's inception.", size: 3.0 },
    { id: "market", name: "Market", x: 26.8, y: 62.3, type: "market", desc: "The Adsuren Market is the centerpiece of the village and what draws in most of the people who visit this humble settlement. The open-air venue is illuminated by lanterns suspended from the sparsely distributed trees, providing ample light to keep the space lively. ", size: 3.0 },
  ],
};
