window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["basctdelm"] = {
  id: "basctdelm",
  name: "basctdelm",
  image: "images/cities/basctdelm/basctdelm.PNG",
  previewImage: "images/cities/basctdelm/basctdelm.PNG",
  pins: [
    { n:  1, x: 10.8, y: 18.5, name: "Talward Keep", type: "Keep", desc: "" },
    { n:  2, x: 14.5, y: 35.7, name: "House of Myr", type: "House", desc: "" },
    { n:  3, x: 26.0, y: 19.9, name: "Talward Garrison", type: "Garrison", desc: "" },
    { n:  4, x: 26.8, y: 37.6, name: "The Queen's Gate", type: "Gate", desc: "" },
    { n:  5, x: 21.6, y: 50.0, name: "Greenscape Park", type: "Park", desc: "" },
    { n:  6, x: 31.1, y: 48.1, name: "Vault of Basctdelm", type: "Vault", desc: "" },
    { n:  7, x: 63.0, y: 47.5, name: "Trader's Market", type: "poi", desc: "" },
    { n:  8, x: 86.0, y: 38.7, name: "The Beacon", type: "poi", desc: "" },
    { n:  9, x: 12.9, y: 45.9, name: "Dripping Dagger Tavern", type: "poi", desc: "" },
    { n: 10, x: 37.0, y: 24.4, name: "Last Prince Inn", type: "poi", desc: "" },
    { n: 11, x: 53.5, y: 48.1, name: "Grey Fiddle Inn", type: "poi", desc: "" },
    { n: 12, x: 67.0, y: 65.1, name: "Haystack Inn", type: "poi", desc: "" },
    { n: 13, x: 73.3, y: 41.2, name: "The Waiting Ship Inn", type: "poi", desc: "" },
    { n: 14, x: 81.6, y: 70.6, name: "Double Mice Inn", type: "poi", desc: "" },
    { n: 15, x: 79.8, y: 80.7, name: "Ye Little Giant Tavern", type: "poi", desc: "" },
    { n: 16, x: 33.9, y: 32.0, name: "Plethora of Possibilities", type: "poi", desc: "" },
    { n: 17, x: 35.4, y: 46.8, name: "Monbereth's Armory", type: "poi", desc: "" },
    { n: 18, x: 35.6, y: 57.2, name: "Strongbow", type: "poi", desc: "" },
    { n: 19, x: 38.6, y: 65.2, name: "Mindful Mix", type: "poi", desc: "" },
    { n: 20, x: 55.0, y: 27.8, name: "Seems So", type: "poi", desc: "" },
    { n: 21, x: 64.3, y: 22.1, name: "Flawless Crafts", type: "poi", desc: "" },
    { n: 22, x: 10.6, y: 84.3, name: "Meadow of the Morning Sun", type: "poi", desc: "" },
    { n: 23, x: 22.5, y: 67.0, name: "Temple of Tiash", type: "poi", desc: "" },
    { n: 24, x: 44.8, y: 52.7, name: "Shrine to Addan", type: "poi", desc: "" },
    { n: 25, x: 32.7, y: 43.4, name: "Braethyn's Archives", type: "Library", desc: "The Braethyn's Archives is the largest library in Basctdelm, comprised of:\nan Admittance Area where visitors are cleared before access to the library, \nthe Main Library where all of the books and scrolls are organized, \nthe Preserved Collection which is the restricted fourth floor where the most valuable archives are stored, and \nthe Undercroft where miscellaneous parchments are used to create the tomes and scrolls of the library. \n" },
    { n: 26, x: 46.6, y: 71.7, name: "One for Everyone", type: "poi", desc: "" },
    { n: 27, x: 52.3, y: 22.8, name: "The Promissory", type: "poi", desc: "" },
    { n: 28, x: 63.2, y: 31.2, name: "Fragrant Plunge", type: "poi", desc: "" },
  ],
  namedLabels: [],
};
