window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["shademoor"] = {
  id: "shademoor",
  name: "Shademoor",
  image: "images/cities/shademoor/shademoor.png",
  previewImage: "images/cities/shademoor/shademoor.png",
  pins: [
    { n:  1, x: 12.6, y: 46.5, name: "The Old Cathedral", type: "Temple", desc: "The Old Cathedral is a historic structure located on the western edge of the Garden, atop the large hill overlooking Shademoor. It is built from grey stone and remarkably well-preserved. The parvis, made of worn but sturdy stone, leads to enormous ornate Shadewood doors adorned with intricate carvings of symbols representing life, death, and rebirth.\n" },
    { n:  2, x: 17.1, y: 34.4, name: "Hero's Tomb", type: "Tomb", desc: "The Hero's Tomb is a solemn collection of three stone mausoleums located on the northern edge of the Garden. These structures were built to honor the most notable warriors and defenders who perished in the Battle of Shademoor. The mausoleums are crafted from grey stone, simple yet sturdy. Carvings of resolute warriors adorn the walls, standing in eternal vigil as silent guardians of those interred within.\n" },
    { n:  3, x: 33.8, y: 87.0, name: "Onmor's Shop", type: "lumber & carpentry", desc: "Onmor's Shop, nestled deep in the Shademoor forest, is a combination lumber shop, carpentry workshop, and storage facility. The shop itself is a relic of skilled craftsmanship, made entirely of Shadewood from the forest and rumored to be as old as the Old Cathedral. The Shadewood planks have aged beautifully, giving the building a petrified appearance that almost glows faintly in dim light. The storage building, a more recent addition, is a large, utilitarian structure designed to house lumber, tools, and completed works." },
    { n:  4, x: 55.4, y: 65.9, name: "Countess' Residence", type: "House", desc: "The Countess's residence is an imposing yet elegant structure with gothic aesthetics. Perched atop a gentle hill to the southeast of town, the two-story rectangular building is constructed from intricately carved stone, with pointed arches and ornate flourishes. The residence is accessible via a small cobblestone road that winds up from the town square." },
    { n:  5, x: 65.9, y: 46.2, name: "Crael's House ", type: "Oratory", desc: "Crael's House is not only a place of worship but also a cornerstone of Shademoor's identity. Built to honor Crael, the god of fate and death, it serves as a space for the townsfolk to offer prayers and seek solace for the departed.  The oratory is overseen by Yestrana Aerhorn, a wise and compassionate half-elven cleric who has dedicated her life to Crael's service. Her two halfling acolytes, Elo Tossbrook and Hani Mosspot, assist with daily rites, upkeep of the oratory, and offering guidance to visitors. Yestrana often leads ceremonies of remembrance and blessings, particularly during burials or anniversaries of the Fracturing's battles. \n" },
    { n:  6, x: 64.2, y: 39.5, name: "The Stock House", type: "Pub and Store", desc: "The Stock House is a cornerstone establishment of Shademoor, combining a general store and a pub under one roof. The two-story building is constructed of dark Shadewood and stone, with the ground floor built entirely of stone to provide a cool, stable base for the pub, while the upper floor, made of polished Shadewood, houses the store. Large double doors open the pub area to the street, inviting patrons to sit and enjoy a drink or meal with a view of the town square." },
    { n:  7, x: 56.8, y: 32.0, name: "Guardhouse", type: "poi", desc: "The guardhouse near Shademoor's town square is a small but practical structure designed to support the town's patrols. Built from sturdy grey stone with a slightly sloping shingle roof, the building has a single room that serves as a rest area and a small storage space for basic supplies, such as spare weapons, torches, and patrol records. " },
    { n:  8, x: 62.5, y: 31.7, name: "Mottleberry Bazaar", type: "Food", desc: "The Mottleberry Bazaar is a vibrant and welcoming shop located on the western edge of the town square in Shademoor. Established shortly after the Awakening, the shop is run by Peveni Illdor, a resourceful halfling from Inverland, and his wife, Bevel Illdor, a cheerful local. The building itself is an eclectic mix of mismatched wood and stone, giving it a quirky and inviting charm that stands out from the more uniform structures of the town square." },
    { n:  9, x: 67.9, y: 29.0, name: "Town Hall", type: "Hall", desc: "The Town Hall of Shademoor is the administrative heart of the town and serves as the central location for governance and public services. Constructed entirely of wood, the structure showcases the rich, dark tones of Shadewood with contrasting accents of pale birch. The main hall occupies the entire central section, extending two stories high and running from the front entrance to the back of the building. To either side of the main hall are stacked rooms, with the upper rooms accessible via staircase in the back corners of the hall. A lofted balcony runs along the second floor on each side, providing a view of the main hall below.\n" },
    { n: 10, x: 72.8, y: 28.4, name: "Fornwulf's", type: "tannery & fletching", desc: "Fornwulf Fletching & Tannery is a thriving partnership between Alluyn Fornwulf and Mordi Orbel, catering to the needs of hunters, adventurers, and townsfolk alike. Alluyn, a skilled wood elf, handles the fletching side of the business, specializing in crafting high-quality bows, arrows, and quivers. His craft is sound, providing both goods and repair services.\n" },
    { n: 11, x: 75.6, y: 37.4, name: "Hollow Root Inn", type: "Inn", desc: "The Hollow Root Inn is a vital hub for Shademoor, serving as the town's primary gathering place and a stopping point for travelers. Run by the Grimric family, the inn thrives on its reputation for its unique Hollow Root Stew, a hearty dish crafted daily by Enan Grimric using ingredients sourced from the town and surrounding area. The stew varies based on available meats, making it a staple of local comfort food." },
    { n: 12, x: 77.4, y: 43.7, name: "Night's Favor", type: "oratory", desc: "The Night's Favor is an oratory dedicated to Phoe, the Hooded Lady, and Sylunara, the Evening Radiance.  The stone and Shadewood structure, adorned with subtle carvings representing phases of the moons and cloaked figures, hints at the secretive and transformative nature of its deities.\n" },
    { n: 13, x: 74.5, y: 52.5, name: "Fiard's Arms & Armor", type: "Smithy", desc: "Fiard's Arms & Armory is the go-to location for weapons and armor in Shademoor, catering to locals, travelers, and adventurers alike. The stone shop is divided into two sections: the circular front room, which serves as the display and sales area, and the rectangular forge at the rear, where Fiard works tirelessly. \n" },
    { n: 14, x: 71.2, y: 74.7, name: "Pirli's Stalls", type: "stables", desc: "Pirli's Stalls is the main stable in Shademoor, located just outside of town square behind the blacksmith. The operation is run by Pirli Sinton, a kind and hard-working widow, with the help of her daughter, Layla, and a quiet but skilled half-orc named Trum. The stables are built from light oak wood and are large enough to house a dozen horses comfortably. The facility includes individual stalls, a small tack room, and a spacious loft where Trum resides. The stable yard is well-maintained, with plenty of space for horses to exercise and graze.\n" },
  ],
  namedLabels: [],
};
