window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["emberstran"] = {
  id: "emberstran",
  name: "Emberstran",
  image: "images/cities/emberstran/emberstran.PNG",
  previewImage: "images/cities/emberstran/emberstran.PNG",
  pins: [
    { n:  1, x: 50.7, y: 38.0, name: "The Lord's Keep", type: "keep", desc: "The seat of power in Emberstran." },
    { n:  2, x: 68.6, y: 27.1, name: "Imonorra's Tower", type: "tower", desc: "A tall tower belonging to the mage Imonorra." },
    { n:  3, x: 78.0, y: 42.0, name: "Cemetery", type: "cemetery", desc: "The city cemetery, maintained by the Temple to Diverra." },
    { n:  4, x: 50.7, y: 45.8, name: "Market", type: "market", desc: "Emberstran's main market square." },
    { n:  5, x: 50.9, y: 71.3, name: "Docks", type: "harbor", desc: "The harbour docks of Emberstran, opening onto the Glimmering Sea.", size: 1.2 },
    { n:  6, x: 50.9, y: 17.6, name: "Upper City Gate", type: "gate", desc: "The main northern gate into Emberstran's upper city.", size: 1.2 },
    { n:  7, x: 11.0, y: 34.0, name: "Western Gate", type: "gate", desc: "Western gate leading toward Flatgarde." },
    { n:  8, x: 95.2, y: 74.8, name: "Southern Gate", type: "gate", desc: "Southern gate leading toward Ulgrey.", size: 1.2 },
    { n:  9, x: 17.6, y: 34.1, name: "The Dyed Cane", type: "tavern", desc: "A lively tavern in the western quarter.", size: 1.1 },
    { n: 10, x: 22.0, y: 42.8, name: "The Headless Hydra", type: "tavern", desc: "A rough-and-tumble tavern popular with dock workers and sailors.", size: 1.2 },
    { n: 11, x: 53.5, y: 66.2, name: "Anchor Point", type: "tavern", desc: "A respectable tavern near the eastern docks.", size: 1.1 },
    { n: 12, x: 63.4, y: 44.4, name: "The Crimson Swan", type: "inn", desc: "Emberstran's finest inn.", size: 1.1 },
    { n: 13, x: 69.3, y: 34.2, name: "Old Oak & Grapes", type: "tavern", desc: "An old establishment with a large oak tree growing through the roof.", size: 1.2 },
    { n: 14, x: 78.8, y: 62.1, name: "Crusty Mug", type: "tavern", desc: "A cheap dockside tavern.", size: 1.1 },
    { n: 15, x: 88.8, y: 67.3, name: "Warm Bear Inn", type: "inn", desc: "A cosy inn in the eastern quarter.", size: 1.2 },
    { n: 16, x: 14.2, y: 42.8, name: "Charum's Oils", type: "Shop", desc: "An apothecary and oil merchant.", size: 1.2 },
    { n: 17, x: 45.4, y: 45.9, name: "Points & Edges", type: "shop", desc: "A weapons and armour merchant near the market square.", size: 1.1 },
    { n: 18, x: 48.1, y: 66.5, name: "The Silver Spaulder", type: "shop", desc: "A high-quality armourer's shop near the docks.", size: 1.1 },
    { n: 19, x: 51.1, y: 63.2, name: "Raddic's Rarities", type: "shop", desc: "A curiosity shop run by the half-elf Raddic.", size: 1.1 },
    { n: 20, x: 55.8, y: 46.0, name: "Gems of Emberstran", type: "shop", desc: "A jeweller and gem merchant.", size: 1.2 },
    { n: 21, x: 20.0, y: 62.3, name: "Lady Luck's Temple", type: "temple", desc: "A temple dedicated to Lady Luck.", size: 1.1 },
    { n: 22, x: 45.0, y: 25.9, name: "Temple to Diverra", type: "temple", desc: "The main temple of Diverra, goddess of the sea and storms.", size: 1.2 },
    { n: 23, x: 75.4, y: 46.9, name: "Church to Crael", type: "temple", desc: "A small church dedicated to Crael, god of fire and forge.", size: 1.2 },
  ],
  namedLabels: [
    { id: "glimmering-sea", name: "The Glimmering Sea", x: 40.0, y: 92.0, type: "sea", desc: "The sea to the south of Emberstran." },
    { id: "to-flatgarde", name: "To Flatgarde", x: 2.0, y: 38.0, type: "direction", desc: "Road leading west to Flatgarde." },
    { id: "to-ulgrey", name: "To Ulgrey", x: 90.0, y: 84.0, type: "direction", desc: "Road leading south to Ulgrey." },
  ],
};
