window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["emberstran"] = {
  id: "emberstran",
  name: "Emberstran",
  image: "images/cities/emberstran/emberstran.PNG",
  previewImage: "images/cities/emberstran/emberstran.PNG",
  pins: [
    { n:  1, x: 50.9, y: 35.9, name: "The Lord's Keep", type: "keep", desc: "The seat of power in Emberstran.", size: 0.7 },
    { n:  2, x: 67.7, y: 25.9, name: "Imonorra's Tower", type: "tower", desc: "A tall tower belonging to the mage Imonorra.", size: 0.7 },
    { n:  3, x: 83.2, y: 36.9, name: "Cemetery", type: "cemetery", desc: "The city cemetery, maintained by the Temple to Diverra.", size: 0.7 },
    { n:  4, x: 50.7, y: 43.8, name: "Market", type: "market", desc: "Emberstran's main market square.", size: 0.7 },
    { n:  5, x: 51.0, y: 68.2, name: "Docks", type: "harbor", desc: "The harbour docks of Emberstran, opening onto the Glimmering Sea.", size: 0.7 },
    { n:  6, x: 50.9, y: 17.6, name: "Upper City Gate", type: "gate", desc: "The main northern gate into Emberstran's upper city.", size: 0.7 },
    { n:  7, x: 11.6, y: 32.0, name: "Western Gate", type: "gate", desc: "Western gate leading toward Flatgarde.", size: 0.7 },
    { n:  8, x: 94.2, y: 70.5, name: "Southern Gate", type: "gate", desc: "Southern gate leading toward Ulgrey.", size: 0.7 },
    { n:  9, x: 17.7, y: 32.6, name: "The Dyed Cane", type: "tavern", desc: "A lively tavern in the western quarter.", size: 0.7 },
    { n: 10, x: 22.0, y: 42.8, name: "The Headless Hydra", type: "tavern", desc: "A rough-and-tumble tavern popular with dock workers and sailors.", size: 0.7 },
    { n: 11, x: 52.9, y: 62.8, name: "Anchor Point", type: "tavern", desc: "A respectable tavern near the eastern docks.", size: 0.7 },
    { n: 12, x: 63.2, y: 42.1, name: "The Crimson Swan", type: "inn", desc: "Emberstran's finest inn.", size: 0.7 },
    { n: 13, x: 69.7, y: 32.7, name: "Old Oak & Grapes", type: "tavern", desc: "An old establishment with a large oak tree growing through the roof.", size: 0.7 },
    { n: 14, x: 78.8, y: 59.1, name: "Crusty Mug", type: "tavern", desc: "A cheap dockside tavern.", size: 0.7 },
    { n: 15, x: 88.6, y: 64.2, name: "Warm Bear Inn", type: "inn", desc: "A cosy inn in the eastern quarter.", size: 0.7 },
    { n: 16, x: 14.5, y: 40.8, name: "Charum's Oils", type: "Shop", desc: "An apothecary and oil merchant.", size: 0.7 },
    { n: 17, x: 45.1, y: 43.7, name: "Points & Edges", type: "shop", desc: "A weapons and armour merchant near the market square.", size: 0.7 },
    { n: 18, x: 48.6, y: 63.0, name: "The Silver Spaulder", type: "shop", desc: "A high-quality armourer's shop near the docks.", size: 0.7 },
    { n: 19, x: 50.7, y: 59.8, name: "Raddic's Rarities", type: "shop", desc: "A curiosity shop run by the half-elf Raddic.", size: 0.7 },
    { n: 20, x: 55.9, y: 43.9, name: "Gems of Emberstran", type: "shop", desc: "A jeweller and gem merchant.", size: 0.7 },
    { n: 21, x: 20.0, y: 62.3, name: "Lady Luck's Temple", type: "temple", desc: "A temple dedicated to Lady Luck.", size: 0.7 },
    { n: 22, x: 45.1, y: 24.0, name: "Temple to Diverra", type: "temple", desc: "The main temple of Diverra, goddess of the sea and storms.", size: 0.7 },
    { n: 23, x: 75.0, y: 44.3, name: "Church to Crael", type: "temple", desc: "A small church dedicated to Crael, god of fire and forge.", size: 0.7 },
  ],
  namedLabels: [
    { id: "glimmering-sea", name: "The Glimmering Sea", x: 40.0, y: 92.0, type: "sea", desc: "The sea to the south of Emberstran." },
    { id: "to-flatgarde", name: "To Flatgarde", x: 2.0, y: 31.2, type: "direction", desc: "Road leading west to Flatgarde." },
    { id: "to-ulgrey", name: "To Ulgrey", x: 97.9, y: 73.4, type: "direction", desc: "Road leading south to Ulgrey." },
  ],
};
