window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["nauldeaus"] = {
  id: "nauldeaus",
  name: "Nauldeaus",
  image: "images/cities/nauldeaus/nauldeaus.PNG",
  previewImage: "images/cities/nauldeaus/nauldeaus.PNG",
  pins: [
    { n:  1, x: 29.1, y: 28.2, name: "Far Warehouse", type: "warehouse", desc: "A large warehouse district on the far edge of the city." },
    { n:  2, x: 45.2, y: 60.6, name: "Trader's Market", type: "market", desc: "The main trading market of Nauldeaus." },
    { n:  3, x: 52.8, y: 70.6, name: "The Meridian's Seat", type: "landmark", desc: "Seat of the city's ruling council." },
    { n:  4, x: 61.4, y: 74.5, name: "Wave's Edge Vault", type: "bank", desc: "The city's primary vault and financial institution." },
    { n:  5, x: 61.6, y: 51.1, name: "Wave's Edge Theater", type: "theater", desc: "The city's main performance theater." },
    { n:  6, x: 50.0, y: 50.0, name: "Wave's Edge Keep", type: "keep", desc: "The fortified keep of Nauldeaus." },
    { n:  7, x: 81.9, y: 23.3, name: "Wave's Lantern", type: "landmark", desc: "A great lighthouse marking the harbor entrance." },
    { n:  8, x: 92.6, y: 62.4, name: "The Overlook", type: "landmark", desc: "A high point with views over the city and sea." },
    { n:  9, x: 21.3, y: 21.0, name: "Stacked Cask Brewery", type: "tavern", desc: "A popular brewery and tavern." },
    { n: 10, x: 33.4, y: 32.8, name: "The Ship House", type: "tavern", desc: "A nautical-themed tavern near the dots." },
    { n: 11, x: 39.0, y: 69.0, name: "Gabük Brothers", type: "shop", desc: "A well-stocked general goods shop run by two brothers." },
    { n: 12, x: 38.6, y: 77.2, name: "Wave's Edge Novelties", type: "shop", desc: "Unusual and imported goods from across the seas." },
    { n: 13, x: 48.4, y: 56.3, name: "Dren's Worn Anvil", type: "shop", desc: "A blacksmith and armorer." },
    { n: 14, x: 55.0, y: 54.0, name: "Old Hand Outfitter", type: "shop", desc: "Outfitting supplies for sailors and travelers." },
    { n: 15, x: 81.3, y: 75.5, name: "Flask of Fuena", type: "tavern", desc: "A tavern named for a local spirit." },
    { n: 16, x: 23.8, y: 38.6, name: "Dockside", type: "inn", desc: "A reliable inn beside the docks." },
    { n: 17, x: 30.1, y: 77.4, name: "The Bright Pearl", type: "inn", desc: "A well-regarded inn in the merchant quarter." },
    { n: 18, x: 41.7, y: 53.6, name: "Slibberwell", type: "inn", desc: "A modest but clean inn." },
    { n: 19, x: 52.3, y: 62.2, name: "Clam Tarts", type: "tavern", desc: "A pub famous for its clam tarts." },
    { n: 20, x: 67.3, y: 75.2, name: "Broken Oar", type: "inn", desc: "A sailors' inn with a broken oar above the door." },
    { n: 21, x: 13.8, y: 38.0, name: "Shrine to Cembus", type: "shrine", desc: "A small shrine to the god Cembus." },
    { n: 22, x: 45.3, y: 66.5, name: "House of Addan", type: "landmark", desc: "The house of the merchant lord Addan." },
    { n: 23, x: 74.8, y: 48.9, name: "The Sanctum", type: "temple", desc: "A multi-faith sanctum open to all worshippers." },
    { n: 24, x: 75.8, y: 74.7, name: "Shrine of Knowledge", type: "shrine", desc: "A shrine dedicated to learning and knowledge." },
    { n: 25, x: 92.6, y: 65.2, name: "Coralei's Temple", type: "temple", desc: "Temple to Coralei, goddess of the deep." },
    { n: 26, x: 14.9, y: 31.2, name: "Stables", type: "stables", desc: "City stables." },
    { n: 27, x: 24.9, y: 61.7, name: "Bathhouse", type: "bathhouse", desc: "Public bathhouse." },
    { n: 28, x: 57.6, y: 65.3, name: "Triage", type: "medical", desc: "A triage and healing station." },
  ],
  namedLabels: [
    { id: "The-Broken-Deep", name: "The Broken Deep", x: 75.0, y: 6.8, type: "water", desc: "", size: 2.0 },
    { id: "coraleis-overlook", name: "Coralei's Overlook", x: 94.1, y: 56.4, type: "Sea", desc: "", size: 2.0 },
    { id: "upper-gate", name: "Upper Gate", x: 67.5, y: 87.5, type: "Gate", desc: "", size: 2.0 },
    { id: "fast-upper", name: "East Upper", x: 77.4, y: 78.6, type: "Region", desc: "", size: 2.0 },
    { id: "mainway", name: "Mainway", x: 65.5, y: 58.5, type: "Sea", desc: "", size: 2.0 },
    { id: "mainway-loop", name: "Mainway Loop", x: 63.7, y: 47.7, type: "Sea", desc: "", size: 1.7 },
    { id: "west-upper", name: "West Upper", x: 55.1, y: 76.9, type: "Sea", desc: "", size: 2.0 },
    { id: "highward", name: "Highward", x: 31.2, y: 75.4, type: "Sea", desc: "", size: 2.0 },
    { id: "trade-way", name: "Trade Way", x: 35.5, y: 58.8, type: "Sea", desc: "", size: 2.0 },
    { id: "main-docks", name: "Main Docks", x: 35.8, y: 47.1, type: "Sea", desc: "", size: 2.0 },
    { id: "river-pass", name: "River Pass", x: 22.3, y: 55.7, type: "Sea", desc: "", size: 1.8 },
    { id: "dibaryn-river", name: "Dibaryn River", x: 7.8, y: 78.1, type: "River", desc: "", size: 1.9 },
    { id: "far-docks", name: "Far Docks", x: 34.5, y: 40.1, type: "Sea", desc: "", size: 2.0 },
    { id: "far-ward", name: "Far Ward", x: 24.9, y: 17.3, type: "Sea", desc: "", size: 2.0 },
    { id: "far-gate", name: "Far Gate", x: 4.6, y: 30.3, type: "Gate", desc: "", size: 2.0 },
  ],
};
