window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["onaren"] = {
  id: "onaren",
  name: "Onaren",
  image: "images/cities/onaren/onaren.PNG",
  previewImage: "images/cities/onaren/onaren.PNG",
  pins: [
    { n:  1, x: 30.0, y: 25.9, name: "Evonstride Stables", type: "Stables", desc: "The Evonstride Stables serve as the primary care facility for horses and mounts in O'naren. Attached to the Evonstride family home, the stables are well-maintained, with intricately carved wooden walls supported by sturdy stone columns.", size: 1.4 },
    { n:  2, x: 42.3, y: 23.7, name: "The Overlook", type: "Overlook", desc: "The Overlook in O'naren is a tall, round stone tower situated on the northwestern edge of Driftglow Pond, serving as both a vantage point for the Realmwardens and a communal hub for travelers and merchants.", size: 1.4 },
    { n:  3, x: 72.2, y: 20.7, name: "Temple of Tranquility", type: "Temple", desc: "The Temple of Tranquility is one of the largest and most revered structures in O'naren, standing on a terrace overlooking the northeastern side of town. It is built from smooth stone with intricate floral carvings.", size: 1.4 },
    { n:  4, x: 88.5, y: 23.8, name: "Nestling Soar", type: "Inn", desc: "The Nestling Soar is a well-kept elven inn situated on the upper terrace of northeast O'naren, offering travelers a quiet and comfortable place to stay.", size: 1.4 },
    { n:  5, x: 90.3, y: 39.8, name: "Truffle Trap, The", type: "poi", desc: "The Truffle Trap is the main tavern in O'naren, sitting adjacent to the Nestling Soar on the upper terrace. A four-story circular tower extends from its right side, giving the establishment a unique architectural touch.", size: 1.4 },
    { n:  6, x: 89.0, y: 47.1, name: "Hall of O'naren", type: "poi", desc: "The Hall of O'naren serves as the center of governance for the town and the seat of Lord Itham Elle'neros.", size: 1.4 },
    { n:  7, x: 72.6, y: 70.6, name: "Commons Area", type: "poi", desc: "The Commons Area is a tranquil clearing on the first terrace in the southeastern part of O'naren. At its center stands a large stone gazebo with a clear view of the cascading falls that feed the Driftglow pond.", size: 1.4 },
    { n:  8, x: 62.3, y: 80.1, name: "Purposeful Poise", type: "Shop", desc: "The stylist's parlor in O'naren is an elegant establishment catering to those who seek refinement and personal grooming.", size: 1.4 },
    { n:  9, x: 55.5, y: 83.2, name: "Pieces of Ra'lorn", type: "Tailor", desc: "The tailor's shop is an elegant establishment catering primarily to elven fashion, known for its expertise in elven garments.", size: 1.4 },
    { n: 10, x: 87.0, y: 85.9, name: "Oracle", type: "Seer", desc: "The Oracle, Zanasee Tsal'daree, is known as the Weavereader, a magic user with deep ties in the Tegenwald Phet. A circular two-story structure on the upper terrace of O'naren.", size: 1.4 },
    { n: 11, x: 44.3, y: 90.4, name: "Fletcher / Tannery", type: "Tannery", desc: "Two well-maintained stone buildings dedicated to the needs of hunters and woodsmen. The Fletcher is a workshop where bows and arrows are skillfully crafted.", size: 1.4 },
    { n: 12, x: 32.9, y: 88.4, name: "Vocehna's Gallery", type: "poi", desc: "Vocehna Maepholaer's art gallery is on the upper terrace of O'naren, housed in a square, single-story building with smooth carved stone walls rising to a 20-foot ceiling.", size: 1.4 },
    { n: 13, x: 30.9, y: 75.4, name: "Ore Masters", type: "poi", desc: "The Ore Masters is the collective name for three connected buildings operated by the Tu'osaar siblings, housing an armorsmith, a jeweler, and a weaponsmith.", size: 1.4 },
    { n: 14, x: 23.9, y: 62.5, name: "Mines", type: "mines", desc: "The mines of O'naren are located on the southwest side of town, where a cave entrance opens into the rocky foothills.", size: 1.4 },
    { n: 15, x: 25.2, y: 45.8, name: "Welthas' Market", type: "Store", desc: "The general store in O'naren is a two-story structure, well-stocked with essentials such as rations, travel gear, simple tools, and common goods.", size: 1.4 },
  ],
  namedLabels: [],
};
