window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["scarwatch-hold"] = {
  id: "scarwatch-hold",
  name: "Scarwatch Hold",
  image: "images/cities/scarwatch-hold/scarwatch-hold.png",
  previewImage: "images/cities/scarwatch-hold/scarwatch-hold.png",
  pins: [
    { n:  1, x: 43.2, y: 73.4, name: "Outer Gatehouse", type: "Gate", desc: "This gatehouse is the first stop for those seeking to enter the Scarwatch Hold. The guards here greet outsiders, watch for potential threats, and permit entrance to citizens and peaceful visitors.", size: 1.4 },
    { n:  2, x: 52.6, y: 62.0, name: "Barn & Stables", type: "poi", desc: "The Barn & Stables shelter the Hold's livestock. It also serves merchants and travelers who need a place to shelter their mounts and wagons while visiting the Hold. Animals housed here receive a box stall or pen, food, and grooming.  Animals are well taken care of in this clean, roomy location.", size: 1.4 },
    { n:  3, x: 20.6, y: 59.0, name: "Private Apartments", type: "House", desc: "Folks live here", size: 1.4 },
    { n:  4, x: 31.7, y: 57.5, name: "Smithy", type: "Smithy", desc: "Sells and crafts metal tools, armor, equipment and weapons.", size: 1.4 },
    { n:  5, x: 31.6, y: 52.0, name: "Ilho's Gems", type: "Shop", desc: "Jewelry and Gems are sold here", size: 1.4 },
    { n:  6, x: 31.4, y: 46.3, name: "General Goods", type: "poi", desc: "", size: 1.4 },
    { n:  7, x: 31.0, y: 37.5, name: "Merchantile", type: "poi", desc: "", size: 1.4 },
    { n:  8, x: 19.8, y: 36.0, name: "Bank", type: "poi", desc: "The Hold's residents and visitors store their most valuable belongings and savings in the bank.  This bank is not part of the Realm Depository & Exchange System that exists in other locations in Myrdae.  The bank relies on the Hold's soldiers for protection.  Guards rotate shifts here each harmon, but most don't want this assignment because there isn't much to do.\n", size: 1.4 },
    { n:  9, x: 29.4, y: 27.9, name: "Trader's Market", type: "Market", desc: "You can find basic supplies, groceries and various goods here.", size: 1.4 },
    { n: 10, x: 41.9, y: 19.6, name: "The Hoot & Howl Tavern", type: "Tavern", desc: "The food served here ", size: 1.4 },
    { n: 11, x: 51.4, y: 24.2, name: "Sanctuary", type: "poi", desc: "", size: 1.4 },
    { n: 12, x: 41.9, y: 30.7, name: "Watchtower Inn", type: "Inn", desc: "Can find lodging here", size: 1.4 },
    { n: 13, x: 44.7, y: 47.2, name: "Scarwatch House", type: "poi", desc: "", size: 1.4 },
    { n: 14, x: 57.3, y: 43.5, name: "Inner Gatehouse", type: "Gate", desc: "This gatehouse houses on-duty soldiers and separates the civilian areas of the Hold from the Palisades and Citadel.", size: 1.4 },
    { n: 15, x: 72.1, y: 42.1, name: "Palisades", type: "POI", desc: "The sheltered palisades are where the Hold's defenders live and practice combat drills.", size: 1.4 },
    { n: 16, x: 86.4, y: 43.5, name: "Citadel", type: "poi", desc: "The Warden governs the Hold from its Citadel, a stone stronghold solidly built to withstand assault. Multiple towers rise above the main building, which is 30 feet tall. The citadel shelters emergency resources, municipal chambers, and the Hold's armed forces. Militaristic banners and upholstered furniture decorate its dignified interior.", size: 1.4 },
    { n: 17, x: 74.7, y: 24.3, name: "Performance/Jousting Field", type: "poi", desc: "This area serves as a training ground most days, but also houses tournaments that generally take place each harmon. ", size: 1.4 },
  ],
  namedLabels: [],
};
