window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["tratta"] = {
  id: "tratta",
  name: "Tratta",
  image: "images/cities/tratta/tratta.PNG",
  previewImage: "images/tratta.jpg",
  pins: [
    { n:  1, x: 41.1, y: 26.2, name: "The Anchored Spire", type: "Tavern", desc: "A well-known tavern and meeting point in the heart of Tratta's upper ring." },
    { n:  2, x: 32.0, y: 50.7, name: "SeaRoute Colosseum", type: "arena", desc: "Tratta's grand fighting arena. Gladiatorial bouts, beast fights, and spectacle draw crowds from across Yearning Vale.", size: 1.3 },
    { n:  3, x: 25.4, y: 71.9, name: "Torguard Post", type: "garrison", desc: "City guard outpost on the western edge of Tratta. Watches the Westpost approaches and the outer gate.", size: 1.4 },
    { n:  4, x: 52.3, y: 72.0, name: "The Majestic", type: "inn", desc: "Tratta's finest inn. Lavish rooms, a respected dining hall, and discretion guaranteed for wealthy guests.", size: 1.6 },
    { n:  5, x: 63.0, y: 74.5, name: "Travane College", type: "college", desc: "One of two Travane College campuses in Tratta.", size: 1.4 },
    { n:  6, x: 76.2, y: 76.1, name: "The Reserve (Vault)", type: "bank", desc: "Tratta's most secure financial institution. Houses gold reserves, trade bonds, and sealed private vaults.", size: 1.5 },
    { n:  7, x: 59.0, y: 28.3, name: "Lower Warehouse", type: "warehouse", desc: "Large storage facility serving the lower dock district.", size: 1.4 },
    { n:  8, x: 49.1, y: 39.7, name: "Slippy Tails", type: "tavern", desc: "A rowdy dockside tavern popular with fishermen and sailors off the Lower Docks.", size: 1.4 },
    { n:  9, x: 44.7, y: 14.1, name: "Ye Olde Elderberry", type: "tavern", desc: "A venerable drinking establishment in the north ward.", size: 1.3 },
    { n: 10, x: 39.0, y: 33.8, name: "Sticky Parrot", type: "tavern", desc: "Lively tavern in the inner ring.", size: 1.4 },
    { n: 11, x: 22.7, y: 44.8, name: "SeaRoute Inn", type: "inn", desc: "Affordable lodging for traveling merchants following the sea trade routes.", size: 1.5 },
    { n: 12, x: 46.9, y: 66.3, name: "Mahl's Hold", type: "stronghold", desc: "A secondary fortified compound belonging to the Mahl dynasty.", size: 1.5 },
    { n: 13, x: 67.6, y: 52.8, name: "Trusty Tankard", type: "tavern", desc: "Sailor's tavern on the eastern dock strip.", size: 1.3 },
    { n: 14, x: 70.2, y: 82.8, name: "The Zealous Crew", type: "tavern", desc: "Favored by privateers and naval officers alike.", size: 1.5 },
    { n: 15, x: 52.0, y: 30.2, name: "Lower Market", type: "market", desc: "The main street market of the lower ring.", size: 1.5 },
    { n: 16, x: 31.2, y: 37.9, name: "Trade Shops", type: "market", desc: "A cluster of permanent trade shops near the harbor entry.", size: 1.5 },
    { n: 17, x: 43.5, y: 58.9, name: "Soren's Oddities", type: "shop", desc: "A curiosity shop run by the enigmatic Soren.", size: 1.6 },
    { n: 18, x: 65.4, y: 58.9, name: "High Market", type: "market", desc: "The upscale market district.", size: 1.5 },
    { n: 19, x: 68.3, y: 87.4, name: "Travane College", type: "college", desc: "Second campus of Travane College, southern district.", size: 1.4 },
    { n: 20, x: 69.2, y: 38.9, name: "Broken Sea Pearl", type: "inn", desc: "An inn with harbor views.", size: 1.5 },
    { n: 21, x: 32.2, y: 30.9, name: "Shrine of Knowledge", type: "shrine", desc: "A small but respected shrine dedicated to the pursuit of knowledge.", size: 1.4 },
    { n: 22, x: 20.9, y: 26.3, name: "Statue of Brault", type: "landmark", desc: "A large bronze statue of Brault the Navigator.", size: 1.6 },
    { n: 23, x: 68.1, y: 62.6, name: "Temple of Tratta", type: "temple", desc: "The city's primary temple.", size: 1.6 },
    { n: 24, x: 40.6, y: 84.7, name: "Stables", type: "stables", desc: "City stables in the southwest quarter.", size: 1.7 },
    { n: 25, x: 48.0, y: 17.2, name: "Bathhouse", type: "bathhouse", desc: "Public bathhouse in the upper ring.", size: 1.4 },
    { n: 26, x: 40.7, y: 76.0, name: "Triage", type: "medical", desc: "A triage and healing station in the lower ring.", size: 1.5 },
    { n: 27, x: 83.9, y: 68.8, name: "Lovely Loft", type: "brothel", desc: "Tratta's most notable brothel, near the harbor.", size: 1.5 },
    { n: 24, x: 13.1, y: 34.9, name: "Stables", type: "poi", desc: "", size: 1.4 },
    { n: 21, x: 20.1, y: 50.6, name: "Shrine of Knowledge", type: "poi", desc: "", size: 1.4 },
  ],
  namedLabels: [
    { id: "north-gate", name: "North Gate", x: 50.3, y: 5.8, type: "gate", desc: "Primary northern entrance to Tratta." },
    { id: "westpost", name: "Westpost", x: 4.1, y: 44.0, type: "district", desc: "The outer western settlement beyond the walls." },
    { id: "lower-docks", name: "Lower Docks", x: 55.9, y: 39.8, type: "harbor", desc: "Inner harbor sheltered from the Broken Deep." },
    { id: "high-decks", name: "High Decks", x: 61.7, y: 45.0, type: "harbor", desc: "Deep-water berths for ocean-going vessels." },
    { id: "mahl-palace", name: "Mahl Palace", x: 89.7, y: 56.5, type: "palace", desc: "Seat of the Mahl dynasty." },
    { id: "high-gate", name: "High Gate", x: 77.1, y: 90.6, type: "gate", desc: "Southern gate connecting Tratta to Yearning Vale." },
    { id: "broken-deep", name: "The Broken Deep", x: 83.5, y: 19.0, type: "sea", desc: "Treacherous coastal waters east of Tratta." },
  ],
};
