window.CITY_MAPS_REGISTRY = window.CITY_MAPS_REGISTRY || {};
window.CITY_MAPS_REGISTRY["ulgrey"] = {
  id: "ulgrey",
  name: "Ulgrey",
  image: "images/cities/ulgrey/ulgrey.png?v=2",
  previewImage: "images/cities/ulgrey/ulgrey.png?v=2",
  pins: [
    { n:  1, x: 53.1, y: 9.5, name: "Torec's Circle", type: "temple", desc: "Torec’s Circle is one of the oldest and most spiritually significant locations in Ulgrey. The monumental stones were raised by the village’s original settlers when they turned from the Hooded Lady (Phoe) to the worship of the elemental god Torec. Paeris Iya’ren, the moon elf wizard, was directly involved in the raising and consecration of the circle." },
    { n:  2, x: 68.8, y: 8.1, name: "Graveyard", type: "poi", desc: "The Ulgrey Graveyard sits on the northeastern side of the village along the riverbank. Many of the graves feature Torec’s Vigil Stones — small bowls or recesses where locals leave offerings of water, ash, earth, or sand to ask the elemental god to watch over their ancestors." },
    { n:  3, x: 94.8, y: 7.0, name: "Ferebert Mill", type: "poi", desc: "The mill’s greatest secret and source of its reputation is its main grindstone, which was carved decades ago from one of the original standing stones of Torec’s Circle with the blessing of Paeris Iya’ren. Many locals believe this gives the stone a minor elemental blessing." },
    { n:  4, x: 68.6, y: 25.5, name: "Stables", type: "poi", desc: "Built years ago by a half-elf named Jeeder Aevendor, the Stables are now managed by his twin children Avidele and Zanlas. The building is unusually large for a village this size, functioning more like a substantial livestock barn than a simple stable. It provides ample covered space for horses, mules, oxen, and other beasts of burden belonging to both villagers and traveling merchants." },
    { n:  5, x: 66.2, y: 36.5, name: "Grabner's Smithy", type: "poi", desc: "Agnes Grabner has run the smithy for over forty years and remains a skilled and respected craftswoman. Roughly twelve years ago she sent her son Gruno north to train with the dwarves of Dunduar. He returned two years ago with advanced dwarven techniques in both forging and metalworking. Together they now produce some of the finest metalwork in the region, ranging from everyday tools and hardware to quality weapons and armor." },
    { n:  6, x: 49.2, y: 30.6, name: "Ulgrey Oratory (Cembus)", type: "poi", desc: "Originally constructed in 1220 as the Church of Neera, this solid stone building was designed in the protective, fortress-like style favored by followers of the goddess of protection. After the Awakening in 1227, when Neera ceased answering prayers, the town’s cleric Zyre Wiscard abandoned Ulgrey in search of answers. The church stood empty for five years." },
    { n:  7, x: 39.2, y: 34.8, name: "Mansion (Leader's house and Town Hall)", type: "poi", desc: "Originally the owners of the Riverdog Inn, the Basser family rose to prominence over the years. Roughly ten years ago they moved from the inn into the Mansion after being asked to take over leadership of the village. Elsie now serves as Burgomaster, while Milton assists her in managing village affairs and maintaining relations with traders and the dwarves of Dunduar." },
    { n:  8, x: 49.6, y: 43.7, name: "Market", type: "poi", desc: "The Crossroads Market operates twice every stretch in the open square at the central crossroads. On market days, the area becomes the lively heart of the village. On off days, the square is largely empty and quiet." },
    { n:  9, x: 55.1, y: 47.0, name: "Solly's Supplies (General Store)", type: "poi", desc: "Solly is a retired adventurer (or eccentric collector) with a compulsion to buy almost anything that doesn’t sell at the Crossroads Market. As a result, her store has become a massive repository of goods. While it looks cluttered and overwhelming to first-time visitors, Solly has an almost supernatural ability to know exactly what she has and where it is." },
    { n: 10, x: 45.9, y: 79.1, name: "Dockhouse", type: "poi", desc: "Orwin Jasce, once a vigorous man, is now quite old but still runs the Dockhouse with the help of his young granddaughter, Loravie. The building no longer functions as the village’s general store. It has been converted into a working fishery and river waystation." },
    { n: 11, x: 51.8, y: 77.5, name: "Riverdog Inn", type: "poi", desc: "The Riverdog Inn is the true heart and oldest structure of Ulgrey. Originally a small dock house and tavern, it has been expanded many times as the village grew. The patchwork of different wood types and architectural styles tells the story of the village’s development.\nFor as long as anyone can remember, the owners of the inn have always kept a dog that freely roams the premises and greets guests arriving from the river or the road. The current owners, Harrek and Shanna Vellor, continue this tradition." },
    { n: 12, x: 64.2, y: 73.0, name: "Paeris' Rise", type: "poi", desc: "This tower is the second oldest building in Ulgrey, constructed shortly after the Riverdog Inn. Paeris Iya’ren, a moon elf wizard with a deep affinity for elemental magic — especially lightning — has lived here for well over a century. She was present during the founding years of the village and personally assisted in the raising and consecration of Torec’s Circle, drawn by the god’s dominion over the elemental forces." },
  ],
  namedLabels: [

  ],
};
